apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: 8000-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080 