apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.imageTage}}:{{ .Values.version }}"
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: {{ .Values.envName }}
        